
export default new Map([
["src/content/docs/contenido/desarrollo/argumentos.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontenido%2Fdesarrollo%2Fargumentos.mdx&astroContentModuleFlag=true")],
["src/content/docs/contenido/desarrollo/metodologia.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontenido%2Fdesarrollo%2Fmetodologia.mdx&astroContentModuleFlag=true")],
["src/content/docs/contenido/anexos/graficas.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontenido%2Fanexos%2Fgraficas.mdx&astroContentModuleFlag=true")],
["src/content/docs/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/contenido/anexos/fuentes.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontenido%2Fanexos%2Ffuentes.mdx&astroContentModuleFlag=true")],
["src/content/docs/contenido/marco_teorico/conceptos.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontenido%2Fmarco_teorico%2Fconceptos.mdx&astroContentModuleFlag=true")],
["src/content/docs/contenido/marco_teorico/estudios.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontenido%2Fmarco_teorico%2Festudios.mdx&astroContentModuleFlag=true")],
["src/content/docs/contenido/introduccion/introduccion.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontenido%2Fintroduccion%2Fintroduccion.mdx&astroContentModuleFlag=true")],
["src/content/docs/contenido/introduccion/resumen.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontenido%2Fintroduccion%2Fresumen.mdx&astroContentModuleFlag=true")],
["src/content/docs/contenido/introduccion/hipotesis.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontenido%2Fintroduccion%2Fhipotesis.mdx&astroContentModuleFlag=true")],
["src/content/docs/contenido/resultados/recomendaciones.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontenido%2Fresultados%2Frecomendaciones.mdx&astroContentModuleFlag=true")],
["src/content/docs/contenido/resultados/conclusion.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontenido%2Fresultados%2Fconclusion.mdx&astroContentModuleFlag=true")],
["src/content/docs/contenido/resultados/resultados.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontenido%2Fresultados%2Fresultados.mdx&astroContentModuleFlag=true")]]);
		